#!/usr/bin/perl
######################################################################
##        Copyright (c) 2014 Carsten Wulff Software, Norway 
## ###################################################################
## Created       : wulff at 2014-12-4
## ###################################################################
## Licensed under the Apache License, Version 2.0 (the "License")
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
## 
##     http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
######################################################################

#- Options
my $cmd = shift;

use FindBin;
use lib "$FindBin::Bin/Lib";

use MakeOcean;
use Extract;
use MakeHtml;
use ParasiticCheck;
use ShowStatus;
use CopySimDir;

my %cmds = (
			ocean => "MakeOcean",
			extract => "Extract",
			html => "MakeHtml",
			status => "ShowStatus",
			copy => "CopySimDir",
			check => "ParasiticCheck",
);


if(exists($cmds{$cmd})){
  my $class = $cmds{$cmd};
  my $obj = new $class();
  $obj->run(@ARGV);
}else{
  print "Possible commands ".join(",",keys(%cmds))."\n";
  die "Could not find command $cmd";
}
